---
# Tor download variables
# ----------------------

# Windows
tor_browser_bundle_windows_filename: "torbrowser-install-10.5.6_en-US.exe"
tor_browser_bundle_windows_sig_filename: "torbrowser-install-10.5.6_en-US.exe.asc"

# macOS
tor_browser_bundle_macos_filename: "TorBrowser-10.5.6-osx64_en-US.dmg"
tor_browser_bundle_macos_sig_filename: "TorBrowser-10.5.6-osx64_en-US.dmg.asc"

# Linux 32bit
tor_browser_bundle_linux32_filename: "tor-browser-linux32-10.5.6_en-US.tar.xz"
tor_browser_bundle_linux32_sig_filename: "tor-browser-linux32-10.5.6_en-US.tar.xz.asc"

# Linux 64bit
tor_browser_bundle_linux64_filename: "tor-browser-linux64-10.5.6_en-US.tar.xz"
tor_browser_bundle_linux64_sig_filename: "tor-browser-linux64-10.5.6_en-US.tar.xz.asc"

tor_signer_keyid: "D9FF06E2"

tor_download_files:
  - { "file": "torbrowser-install-10.5.6_en-US.exe", "sig": "torbrowser-install-10.5.6_en-US.exe.asc" }
  - { "file": "TorBrowser-10.5.6-osx64_en-US.dmg", "sig": "TorBrowser-10.5.6-osx64_en-US.dmg.asc" }
  - { "file": "tor-browser-linux32-10.5.6_en-US.tar.xz", "sig": "tor-browser-linux32-10.5.6_en-US.tar.xz.asc" }
  - { "file": "tor-browser-linux64-10.5.6_en-US.tar.xz", "sig": "tor-browser-linux64-10.5.6_en-US.tar.xz.asc" }
